language: java
after_success:
- mvn javadoc:javadoc
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_API_TOKEN"
    keep-history: true
    local-dir: target/site/
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: "mvn -s .travis/maven-settings.xml deploy -DskipTests -Dmaven.javadoc.skip=true"

cache:
  directories:
  - "$HOME/.m2"
